spring.application.name=tienda-web-express

# === Conexion PostgreSQL ===
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_web_express
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
# 'validate' = NO modifica tu BD, solo verifica que las entidades coincidan con las tablas.
# Como ya creaste la BD con el script SQL, este es el modo seguro.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# === Thymeleaf ===
spring.thymeleaf.cache=false
